/** Payload the MentraOS App sends to POST /mentra/inbound */
export interface InboundMessage {
  /** The transcribed user prompt */
  text: string;
  /** Opaque session identifier generated by the MentraOS App */
  sessionKey: string;
}

/** Plain-text response from the agent, routed back to the MentraOS App */
export interface OutboundResponse {
  text: string;
  sessionKey: string;
}

/** Approval request forwarded to the MentraOS App before a privileged command runs */
export interface ApprovalRequest {
  type: "approval";
  /** Unique approval request ID generated by OpenClaw */
  id: string;
  /** Human-readable description of the command requiring approval */
  command: string;
  sessionKey: string;
}

/** Payload the MentraOS App sends to POST /mentra/approval */
export interface ApprovalDecision {
  /** Matches the id from the corresponding ApprovalRequest */
  id: string;
  decision: "allow-once" | "deny";
  sessionKey: string;
}

/** Union of everything the plugin may POST to the callback URL */
export type CallbackPayload = OutboundResponse | ApprovalRequest;
